/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.passmgr;

import java.awt.Frame;
import com.mycompany.passmgr.sec;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */

public class ky extends javax.swing.JDialog {

    /**
     * Creates new form 
     */
    Frame p;
    Main mn;
    String aP;
    public ky(Frame parent, boolean modal,Main m) {
        super(parent, modal);
        try{
            File file = new File(ky.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
            this.aP = file.getParent()+File.separator+"resources";
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        p=parent;
        initComponents();
        this.setVisible(true);
        aaaaaaaaa.setEchoChar('•');
        mn=m;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bbbbbbb = new javax.swing.JButton();
        aaaaaaaaa = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bbbbbbb.setText("Enter");
        bbbbbbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbbbbbbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(bbbbbbb)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aaaaaaaaa)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aaaaaaaaa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bbbbbbb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getjP1(){
        return asvd;
    }
    private String asvd;
    private void bbbbbbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbbbbbbActionPerformed
        // TODO add your handling code here:
        
        File f = new File(aP+File.separator+"xzlknSWCawn.wszc");
        
        String s = String.valueOf(aaaaaaaaa.getPassword());
        String su;
        try {
            su = sec.decrypt(s, f);
            if(s.equals(su))
        {
            asvd=s;
            p.setVisible(true);
            mn.setAscvxzd(getjP1());
            this.setVisible(false);
        }
        } catch (CryptoException ex) {
            JOptionPane.showMessageDialog(this,"Error: Wrong password!");
        }
    }//GEN-LAST:event_bbbbbbbActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField aaaaaaaaa;
    private javax.swing.JButton bbbbbbb;
    // End of variables declaration//GEN-END:variables
}
