/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.passmgr;
import com.mycompany.passmgr.typ;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.mycompany.passmgr.sec;
import java.awt.Color;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */

    String aP="";
    public Main() {
        try{
            File file = new File(ky.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
            this.aP = file.getParent()+File.separator+"resources";
            initComponents();
        llllllllllllllll.setEchoChar('•');
        tttttttttttttt.setEchoChar('•');
        qqqqqqqqqqq.setEchoChar('•');
        rtl();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }
    private void rtl(){
        ArrayList<String> ss = new ArrayList<String>();
        File[] fs = gAf();
        for(File f : fs){
            ss.add(f.getName());
        }
        String[] sA={};
        sA = ss.toArray(sA);
        cccccccccc.setListData(sA);
        cccccccccccccccccccccc.setListData(sA);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        saafsacszdfzd = new javax.swing.JLayeredPane();
        ccccccccccccccccccccc = new javax.swing.JScrollPane();
        cccccccccc = new javax.swing.JList<>();
        kkkkkkkkkkkkkk = new javax.swing.JLabel();
        ddddddddd = new javax.swing.JButton();
        jjjjjjjjjjjjjj = new javax.swing.JCheckBox();
        mmmmmmmmmmm = new javax.swing.JScrollPane();
        iiiiiiiiiiii = new javax.swing.JTextArea();
        llllllllllllllll = new javax.swing.JPasswordField();
        saafsaeszdfzd = new javax.swing.JLayeredPane();
        iiiiiiiiiiiiiii = new javax.swing.JScrollPane();
        cccccccccccccccccccccc = new javax.swing.JList<>();
        eeeeeeeeeeeeeeeeeeeeeee = new javax.swing.JButton();
        hhhhhhhhhhh = new javax.swing.JButton();
        fffffffffffffffffffffffffffffffffff = new javax.swing.JButton();
        bbbbbbbbbbb = new javax.swing.JTextField();
        gggggggggg = new javax.swing.JTextField();
        wwwwwwwwwwwwww = new javax.swing.JTextField();
        pppppppppp = new javax.swing.JTextField();
        ooooooooooo = new javax.swing.JButton();
        ddddddddddddddddddd = new javax.swing.JButton();
        hhhhhhhhhhhhhhhhhhhhhh = new javax.swing.JSeparator();
        zzzzzzzzzzzzzzzzzzz = new javax.swing.JScrollPane();
        vvvvvvvvvvvvvvvvvvv = new javax.swing.JTextArea();
        zzzzzzzzzzzzz = new javax.swing.JTextField();
        uuuuuuuuuuuuuu = new javax.swing.JButton();
        nnnnnnnnnnnn = new javax.swing.JLabel();
        aaaaaaaaaaaaaaaaaaaaa = new javax.swing.JLabel();
        saafsaeszdlzd = new javax.swing.JLayeredPane();
        rrrrrrrrr = new javax.swing.JLabel();
        ssssssssssssssssss = new javax.swing.JLabel();
        eeeeeeeeeeee = new javax.swing.JCheckBox();
        xxxxxxxxxxxxxxxx = new javax.swing.JCheckBox();
        fffffffffffff = new javax.swing.JButton();
        yyyyyyyyyyyy = new javax.swing.JLabel();
        tttttttttttttt = new javax.swing.JPasswordField();
        qqqqqqqqqqq = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        Tabs.setMaximumSize(new java.awt.Dimension(543, 32767));
        Tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabsStateChanged(evt);
            }
        });

        cccccccccc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        cccccccccc.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ccccccccccValueChanged(evt);
            }
        });
        ccccccccccccccccccccc.setViewportView(cccccccccc);

        kkkkkkkkkkkkkk.setText("Site's name");

        ddddddddd.setText("Type");
        ddddddddd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dddddddddActionPerformed(evt);
            }
        });

        jjjjjjjjjjjjjj.setText("Show Password");
        jjjjjjjjjjjjjj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjjjjjjjjjjjjjActionPerformed(evt);
            }
        });

        mmmmmmmmmmm.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        iiiiiiiiiiii.setEditable(false);
        iiiiiiiiiiii.setColumns(20);
        iiiiiiiiiiii.setRows(5);
        iiiiiiiiiiii.setText("This is a test text. This is a test text. This is a test text.");
        iiiiiiiiiiii.setWrapStyleWord(true);
        iiiiiiiiiiii.setAutoscrolls(false);
        mmmmmmmmmmm.setViewportView(iiiiiiiiiiii);

        saafsacszdfzd.setLayer(ccccccccccccccccccccc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsacszdfzd.setLayer(kkkkkkkkkkkkkk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsacszdfzd.setLayer(ddddddddd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsacszdfzd.setLayer(jjjjjjjjjjjjjj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsacszdfzd.setLayer(mmmmmmmmmmm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsacszdfzd.setLayer(llllllllllllllll, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout saafsacszdfzdLayout = new javax.swing.GroupLayout(saafsacszdfzd);
        saafsacszdfzd.setLayout(saafsacszdfzdLayout);
        saafsacszdfzdLayout.setHorizontalGroup(
            saafsacszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saafsacszdfzdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccccccccccccccccccccc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saafsacszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mmmmmmmmmmm)
                    .addGroup(saafsacszdfzdLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jjjjjjjjjjjjjj, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(ddddddddd))
                    .addGroup(saafsacszdfzdLayout.createSequentialGroup()
                        .addComponent(kkkkkkkkkkkkkk, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(llllllllllllllll))
                .addContainerGap())
        );
        saafsacszdfzdLayout.setVerticalGroup(
            saafsacszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saafsacszdfzdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saafsacszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccccccccccccccccccccc)
                    .addGroup(saafsacszdfzdLayout.createSequentialGroup()
                        .addComponent(kkkkkkkkkkkkkk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(mmmmmmmmmmm, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(llllllllllllllll, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(saafsacszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jjjjjjjjjjjjjj)
                            .addComponent(ddddddddd))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Tabs.addTab("Main", saafsacszdfzd);

        saafsaeszdfzd.setForeground(new java.awt.Color(160, 160, 160));

        cccccccccccccccccccccc.setBackground(new java.awt.Color(200, 255, 255));
        cccccccccccccccccccccc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 3", "Item 4", "Item 5", "Item 3", "Item 4", "Item 5", "Item 3", "Item 4", "Item 5", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        cccccccccccccccccccccc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cccccccccccccccccccccc.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ccccccccccccccccccccccValueChanged(evt);
            }
        });
        iiiiiiiiiiiiiii.setViewportView(cccccccccccccccccccccc);

        eeeeeeeeeeeeeeeeeeeeeee.setText("Generate");
        eeeeeeeeeeeeeeeeeeeeeee.setEnabled(false);
        eeeeeeeeeeeeeeeeeeeeeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeeeeeeeeeeeeeeeeeeeeeeActionPerformed(evt);
            }
        });

        hhhhhhhhhhh.setText("Modify");
        hhhhhhhhhhh.setEnabled(false);
        hhhhhhhhhhh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hhhhhhhhhhhActionPerformed(evt);
            }
        });

        fffffffffffffffffffffffffffffffffff.setText("Delete");
        fffffffffffffffffffffffffffffffffff.setEnabled(false);
        fffffffffffffffffffffffffffffffffff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fffffffffffffffffffffffffffffffffffActionPerformed(evt);
            }
        });

        bbbbbbbbbbb.setToolTipText("Password");

        gggggggggg.setToolTipText("Name");

        wwwwwwwwwwwwww.setEnabled(false);

        pppppppppp.setToolTipText("Password");
        pppppppppp.setEnabled(false);

        ooooooooooo.setText("Generate");
        ooooooooooo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oooooooooooActionPerformed(evt);
            }
        });

        ddddddddddddddddddd.setText("Save");
        ddddddddddddddddddd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dddddddddddddddddddActionPerformed(evt);
            }
        });

        hhhhhhhhhhhhhhhhhhhhhh.setForeground(new java.awt.Color(0, 0, 0));
        hhhhhhhhhhhhhhhhhhhhhh.setOrientation(javax.swing.SwingConstants.VERTICAL);

        vvvvvvvvvvvvvvvvvvv.setColumns(1);
        vvvvvvvvvvvvvvvvvvv.setLineWrap(true);
        vvvvvvvvvvvvvvvvvvv.setRows(5);
        vvvvvvvvvvvvvvvvvvv.setWrapStyleWord(true);
        vvvvvvvvvvvvvvvvvvv.setEnabled(false);
        vvvvvvvvvvvvvvvvvvv.setMaximumSize(new java.awt.Dimension(224, 2147483647));
        zzzzzzzzzzzzzzzzzzz.setViewportView(vvvvvvvvvvvvvvvvvvv);

        zzzzzzzzzzzzz.setToolTipText("Description");

        uuuuuuuuuuuuuu.setText("Deselect");
        uuuuuuuuuuuuuu.setEnabled(false);
        uuuuuuuuuuuuuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uuuuuuuuuuuuuuActionPerformed(evt);
            }
        });

        nnnnnnnnnnnn.setText("Title");

        aaaaaaaaaaaaaaaaaaaaa.setText("Desc");

        saafsaeszdfzd.setLayer(iiiiiiiiiiiiiii, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(eeeeeeeeeeeeeeeeeeeeeee, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(hhhhhhhhhhh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(fffffffffffffffffffffffffffffffffff, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(bbbbbbbbbbb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(gggggggggg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(wwwwwwwwwwwwww, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(pppppppppp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(ooooooooooo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(ddddddddddddddddddd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(hhhhhhhhhhhhhhhhhhhhhh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(zzzzzzzzzzzzzzzzzzz, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(zzzzzzzzzzzzz, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(uuuuuuuuuuuuuu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(nnnnnnnnnnnn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdfzd.setLayer(aaaaaaaaaaaaaaaaaaaaa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout saafsaeszdfzdLayout = new javax.swing.GroupLayout(saafsaeszdfzd);
        saafsaeszdfzd.setLayout(saafsaeszdfzdLayout);
        saafsaeszdfzdLayout.setHorizontalGroup(
            saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saafsaeszdfzdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saafsaeszdfzdLayout.createSequentialGroup()
                        .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(saafsaeszdfzdLayout.createSequentialGroup()
                                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ddddddddddddddddddd)
                                    .addComponent(bbbbbbbbbbb, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ooooooooooo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saafsaeszdfzdLayout.createSequentialGroup()
                                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nnnnnnnnnnnn)
                                    .addComponent(aaaaaaaaaaaaaaaaaaaaa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gggggggggg)
                                    .addComponent(zzzzzzzzzzzzz, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(hhhhhhhhhhhhhhhhhhhhhh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iiiiiiiiiiiiiii, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saafsaeszdfzdLayout.createSequentialGroup()
                        .addComponent(pppppppppp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eeeeeeeeeeeeeeeeeeeeeee))
                    .addComponent(wwwwwwwwwwwwww)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saafsaeszdfzdLayout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addComponent(uuuuuuuuuuuuuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fffffffffffffffffffffffffffffffffff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hhhhhhhhhhh))
                    .addComponent(zzzzzzzzzzzzzzzzzzz))
                .addContainerGap())
        );
        saafsaeszdfzdLayout.setVerticalGroup(
            saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saafsaeszdfzdLayout.createSequentialGroup()
                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(saafsaeszdfzdLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fffffffffffffffffffffffffffffffffff)
                            .addComponent(hhhhhhhhhhh)
                            .addComponent(uuuuuuuuuuuuuu)))
                    .addGroup(saafsaeszdfzdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(saafsaeszdfzdLayout.createSequentialGroup()
                                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gggggggggg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nnnnnnnnnnnn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zzzzzzzzzzzzz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aaaaaaaaaaaaaaaaaaaaa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bbbbbbbbbbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ooooooooooo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ddddddddddddddddddd))
                            .addGroup(saafsaeszdfzdLayout.createSequentialGroup()
                                .addComponent(wwwwwwwwwwwwww, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pppppppppp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eeeeeeeeeeeeeeeeeeeeeee)))))
                    .addComponent(hhhhhhhhhhhhhhhhhhhhhh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saafsaeszdfzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iiiiiiiiiiiiiii, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(zzzzzzzzzzzzzzzzzzz))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Tabs.addTab("Manager", saafsaeszdfzd);

        rrrrrrrrr.setText("Old key");

        ssssssssssssssssss.setText("New key");

        eeeeeeeeeeee.setText("Show Key");
        eeeeeeeeeeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeeeeeeeeeeeActionPerformed(evt);
            }
        });

        xxxxxxxxxxxxxxxx.setText("Show Key");
        xxxxxxxxxxxxxxxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xxxxxxxxxxxxxxxxActionPerformed(evt);
            }
        });

        fffffffffffff.setText("Save");
        fffffffffffff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fffffffffffffActionPerformed(evt);
            }
        });

        saafsaeszdlzd.setLayer(rrrrrrrrr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdlzd.setLayer(ssssssssssssssssss, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdlzd.setLayer(eeeeeeeeeeee, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdlzd.setLayer(xxxxxxxxxxxxxxxx, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdlzd.setLayer(fffffffffffff, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdlzd.setLayer(yyyyyyyyyyyy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdlzd.setLayer(tttttttttttttt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        saafsaeszdlzd.setLayer(qqqqqqqqqqq, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout saafsaeszdlzdLayout = new javax.swing.GroupLayout(saafsaeszdlzd);
        saafsaeszdlzd.setLayout(saafsaeszdlzdLayout);
        saafsaeszdlzdLayout.setHorizontalGroup(
            saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saafsaeszdlzdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rrrrrrrrr)
                    .addComponent(ssssssssssssssssss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qqqqqqqqqqq, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(tttttttttttttt))
                .addGap(18, 18, 18)
                .addGroup(saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eeeeeeeeeeee)
                    .addComponent(xxxxxxxxxxxxxxxx))
                .addGap(132, 132, 132))
            .addGroup(saafsaeszdlzdLayout.createSequentialGroup()
                .addGroup(saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saafsaeszdlzdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(yyyyyyyyyyyy))
                    .addGroup(saafsaeszdlzdLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(fffffffffffff)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saafsaeszdlzdLayout.setVerticalGroup(
            saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saafsaeszdlzdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rrrrrrrrr)
                    .addComponent(eeeeeeeeeeee)
                    .addComponent(tttttttttttttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(saafsaeszdlzdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xxxxxxxxxxxxxxxx)
                    .addComponent(ssssssssssssssssss)
                    .addComponent(qqqqqqqqqqq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fffffffffffff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yyyyyyyyyyyy)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        Tabs.addTab("Key", saafsaeszdlzd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dddddddddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dddddddddActionPerformed
        // TODO add your handling code here:
        try {
            Thread.sleep(2000);
        typ.tpt(String.valueOf(llllllllllllllll.getPassword()));
        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dddddddddActionPerformed

    
    private void eeeeeeeeeeeeeeeeeeeeeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeeeeeeeeeeeeeeeeeeeeeeActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        int index;
        String s = "nkb8MO§qAè[&µW@Xj}l7|g4JwSBG9?Cc!=I.`5éx1rPNçh:#£~iH3zdo\"*]^DàZKp_V/$FURE\\av;u6Qy-)0LTe'mft(Y2s";
        
        String t="";
        for(int i=0;i<16;i++)
        {
            index = random.nextInt(s.length());
            t+=s.charAt(index);
        }
        pppppppppp.setText(t);
    }//GEN-LAST:event_eeeeeeeeeeeeeeeeeeeeeeeActionPerformed

    private void fffffffffffffffffffffffffffffffffffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fffffffffffffffffffffffffffffffffffActionPerformed
        // TODO add your handling code here:
        File file = new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2"+File.separator+cccccccccccccccccccccc.getSelectedValue());
        for(File f : file.listFiles()){
            f.delete();
        }
        file.delete();
        rtl();
    }//GEN-LAST:event_fffffffffffffffffffffffffffffffffffActionPerformed

    private void ccccccccccccccccccccccValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ccccccccccccccccccccccValueChanged
        // TODO add your handling code here:
        hhhhhhhhhhh.setEnabled(true);
        fffffffffffffffffffffffffffffffffff.setEnabled(true);
        eeeeeeeeeeeeeeeeeeeeeee.setEnabled(true);
        uuuuuuuuuuuuuu.setEnabled(true);
        wwwwwwwwwwwwww.setEnabled(true);
        pppppppppp.setEnabled(true);
        vvvvvvvvvvvvvvvvvvv.setBackground(gc);
        vvvvvvvvvvvvvvvvvvv.setEnabled(true);
        
        gggggggggg.setEnabled(false);
        zzzzzzzzzzzzz.setEnabled(false);
        bbbbbbbbbbb.setEnabled(false);
        ooooooooooo.setEnabled(false);
        ddddddddddddddddddd.setEnabled(false);
        sIfM = cccccccccccccccccccccc.getSelectedValue();
    }//GEN-LAST:event_ccccccccccccccccccccccValueChanged

    private void eeeeeeeeeeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeeeeeeeeeeeActionPerformed
        // TODO add your handling code here:
        if(eeeeeeeeeeee.isSelected())
        {
            tttttttttttttt.setEchoChar((char)0);
        }else{
            tttttttttttttt.setEchoChar('•');
        }
    }//GEN-LAST:event_eeeeeeeeeeeeActionPerformed

    private void jjjjjjjjjjjjjjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjjjjjjjjjjjjjActionPerformed
        // TODO add your handling code here:
        if(jjjjjjjjjjjjjj.isSelected())
        {
            llllllllllllllll.setEchoChar((char)0);
        }else{
            llllllllllllllll.setEchoChar('•');
        }
    }//GEN-LAST:event_jjjjjjjjjjjjjjActionPerformed

    private void xxxxxxxxxxxxxxxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xxxxxxxxxxxxxxxxActionPerformed
        // TODO add your handling code here:
        if(xxxxxxxxxxxxxxxx.isSelected())
        {
            qqqqqqqqqqq.setEchoChar((char)0);
        }else{
            qqqqqqqqqqq.setEchoChar('•');
        }
    }//GEN-LAST:event_xxxxxxxxxxxxxxxxActionPerformed

    private void rAi(String s){
        File[] fs = gAf();
        for(File f : fs){
            try{
                File file1 = new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2"+File.separator+f.getName()+File.separator+"dvkqzdfhzd.dznts");
                String d = sec.decrypt(ascvxzd,file1);
                File file2 = new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2"+File.separator+f.getName()+File.separator+"jsbdvgyjhzdgf.dznts");
                String p = sec.decrypt(ascvxzd,file2);
                sec.encrypt(s, d, file1);
                sec.encrypt(s, p, file2);
            }catch(CryptoException e){
                
            }
            
        }
    }
    private void fffffffffffffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fffffffffffffActionPerformed
        // TODO add your handling code here:
        File f = new File(aP+File.separator+"xzlknSWCawn.wszc");
        String s = String.valueOf(tttttttttttttt.getPassword());
        String s2 = String.valueOf(qqqqqqqqqqq.getPassword());
        String su;
        try {
            su = sec.decrypt(ascvxzd, f);
            if(s.equals(su))
        {
            if(s2.length()==16){
            rAi(s2);
            ascvxzd=s2;
            sec.encrypt(s2, s2, f);
            yyyyyyyyyyyy.setText("Done!");
            
            }else{
                yyyyyyyyyyyy.setText("Key must be 16 characters long!");
            }
            }else{yyyyyyyyyyyy.setText("Wrong Old Key!");}
            
        } catch (CryptoException ex) {
            
            Logger.getLogger(ky.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_fffffffffffffActionPerformed
    
    private void oooooooooooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oooooooooooActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        int index;
        String s = "nkb8MO§qAè[&µW@Xj}l7|g4JwSBG9?Cc!=I.`5éx1rPNçh:#£~iH3zdo\"*]^DàZKp_V/$FURE\\av;u6Qy-)0LTe'mft(Y2s";
        
        String t="";
        for(int i=0;i<16;i++)
        {
            index = random.nextInt(s.length());
            t+=s.charAt(index);
        }
        bbbbbbbbbbb.setText(t);
    }//GEN-LAST:event_oooooooooooActionPerformed
    private File[] gAf(){
        File file = new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2");
        File[] directories = file.listFiles(new FilenameFilter() {
            
            @Override
            public boolean accept(File current, String name) {
                return new File(current, name).isDirectory();
            }
        });
        return directories;
    }
    private void TabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabsStateChanged
        // TODO add your handling code here:
        if(Tabs.getSelectedIndex()!=2) yyyyyyyyyyyy.setText("");;
    }//GEN-LAST:event_TabsStateChanged

    private void dddddddddddddddddddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dddddddddddddddddddActionPerformed
        // TODO add your handling code here:
        if(gggggggggg.getText().equals("")||bbbbbbbbbbb.getText().equals("")||zzzzzzzzzzzzz.getText().equals("")){
            System.out.println("One field or more is empty");
        }else{
            snp(gggggggggg.getText(),zzzzzzzzzzzzz.getText(),bbbbbbbbbbb.getText());
        }
        rtl();
    }//GEN-LAST:event_dddddddddddddddddddActionPerformed
    
    private static String ascvxzd;
    public void setAscvxzd(String s){
        ascvxzd=s;
    }
    private void snp(String tt,String dsc,String ps){
        File file = new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2"+File.separator+tt);
        if(file.exists()){
            JOptionPane.showMessageDialog(this, "That item already exists, consider using the Modify section.");
        }else{
            file.mkdir();
            try{
                File f1 = new File(file.getAbsolutePath()+File.separator+"dvkqzdfhzd.dznts");
                f1.createNewFile();
                sec.encrypt(ascvxzd, dsc, f1);
                File f2 = new File(file.getAbsolutePath()+File.separator+"jsbdvgyjhzdgf.dznts");
                f2.createNewFile();
                sec.encrypt(ascvxzd, ps, f2);
            }catch(Exception e){
                System.out.println("Error" + e.getMessage());}
        }
    }
    
    private void dAs(String t){
        File file = new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2"+File.separator+t);
        try{
                kkkkkkkkkkkkkk.setText(t);
                File f1 = new File(file.getAbsolutePath()+File.separator+"dvkqzdfhzd.dznts");
                iiiiiiiiiiii.setText(sec.decrypt(ascvxzd, f1));
                File f2 = new File(file.getAbsolutePath()+File.separator+"jsbdvgyjhzdgf.dznts");
                llllllllllllllll.setText(sec.decrypt(ascvxzd, f2));
                
            }catch(Exception e){
                System.out.println("Error" + e.getMessage());}
    }
    Color gc = new Color(200,255,255);
    Color wc = new Color(255,255,255);
    private void mLi(String ot,String t,String dsc,String ps){
        File file = new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2"+File.separator+ot);
        try{      
                if(!t.isEmpty()){
                    File n= new File(aP+File.separator+"s9LKt1Y68V5Gj5KljV2"+File.separator+t);
                    if(file.renameTo(n)){
                        JOptionPane.showMessageDialog(this, "Renamed successfully!");
                        file= n;
                    }else{
                        JOptionPane.showMessageDialog(this, "An item with that name already exists.");
                    }
                }
                if(!dsc.isEmpty()){
                    File f1 = new File(file.getAbsolutePath()+File.separator+"dvkqzdfhzd.dznts");
                    f1.delete();
                    f1.createNewFile();
                    sec.encrypt(ascvxzd, dsc, f1);
                }
                if(!ps.isEmpty()){
                    File f2 = new File(file.getAbsolutePath()+File.separator+"jsbdvgyjhzdgf.dznts");
                    f2.delete();
                    f2.createNewFile();
                    sec.encrypt(ascvxzd, ps, f2);
                }
                
            }catch(Exception e){
                System.out.println("Error" + e.getMessage());}
    }
    private String sIfM;
    private void hhhhhhhhhhhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hhhhhhhhhhhActionPerformed
        // TODO add your handling code here:
        mLi(sIfM,wwwwwwwwwwwwww.getText(),vvvvvvvvvvvvvvvvvvv.getText(),pppppppppp.getText());
        rtl();
        dTdS();
    }//GEN-LAST:event_hhhhhhhhhhhActionPerformed
    private void dTdS(){
        cccccccccccccccccccccc.clearSelection();
        wwwwwwwwwwwwww.setText("");
        pppppppppp.setText("");
        vvvvvvvvvvvvvvvvvvv.setText("");
        hhhhhhhhhhh.setEnabled(false);
        fffffffffffffffffffffffffffffffffff.setEnabled(false);
        eeeeeeeeeeeeeeeeeeeeeee.setEnabled(false);
        uuuuuuuuuuuuuu.setEnabled(false);
        wwwwwwwwwwwwww.setEnabled(false);
        pppppppppp.setEnabled(false);
        vvvvvvvvvvvvvvvvvvv.setBackground(wc);
        vvvvvvvvvvvvvvvvvvv.setEnabled(false);
        
        gggggggggg.setEnabled(true);
        zzzzzzzzzzzzz.setEnabled(true);
        bbbbbbbbbbb.setEnabled(true);
        ooooooooooo.setEnabled(true);
        ddddddddddddddddddd.setEnabled(true);
    }
    private void uuuuuuuuuuuuuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uuuuuuuuuuuuuuActionPerformed
        // TODO add your handling code here:
        dTdS();
    }//GEN-LAST:event_uuuuuuuuuuuuuuActionPerformed

    private void ccccccccccValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ccccccccccValueChanged
        // TODO add your handling code here:
        dAs(cccccccccc.getSelectedValue());
    }//GEN-LAST:event_ccccccccccValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Main m = new Main();
                ky k = new ky(m,false,m);
                ascvxzd = k.getjP1();
           }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel aaaaaaaaaaaaaaaaaaaaa;
    private javax.swing.JTextField bbbbbbbbbbb;
    private javax.swing.JList<String> cccccccccc;
    private javax.swing.JScrollPane ccccccccccccccccccccc;
    private javax.swing.JList<String> cccccccccccccccccccccc;
    private javax.swing.JButton ddddddddd;
    private javax.swing.JButton ddddddddddddddddddd;
    private javax.swing.JCheckBox eeeeeeeeeeee;
    private javax.swing.JButton eeeeeeeeeeeeeeeeeeeeeee;
    private javax.swing.JButton fffffffffffff;
    private javax.swing.JButton fffffffffffffffffffffffffffffffffff;
    private javax.swing.JTextField gggggggggg;
    private javax.swing.JButton hhhhhhhhhhh;
    private javax.swing.JSeparator hhhhhhhhhhhhhhhhhhhhhh;
    private javax.swing.JTextArea iiiiiiiiiiii;
    private javax.swing.JScrollPane iiiiiiiiiiiiiii;
    private javax.swing.JCheckBox jjjjjjjjjjjjjj;
    private javax.swing.JLabel kkkkkkkkkkkkkk;
    private javax.swing.JPasswordField llllllllllllllll;
    private javax.swing.JScrollPane mmmmmmmmmmm;
    private javax.swing.JLabel nnnnnnnnnnnn;
    private javax.swing.JButton ooooooooooo;
    private javax.swing.JTextField pppppppppp;
    private javax.swing.JPasswordField qqqqqqqqqqq;
    private javax.swing.JLabel rrrrrrrrr;
    private javax.swing.JLayeredPane saafsacszdfzd;
    private javax.swing.JLayeredPane saafsaeszdfzd;
    private javax.swing.JLayeredPane saafsaeszdlzd;
    private javax.swing.JLabel ssssssssssssssssss;
    private javax.swing.JPasswordField tttttttttttttt;
    private javax.swing.JButton uuuuuuuuuuuuuu;
    private javax.swing.JTextArea vvvvvvvvvvvvvvvvvvv;
    private javax.swing.JTextField wwwwwwwwwwwwww;
    private javax.swing.JCheckBox xxxxxxxxxxxxxxxx;
    private javax.swing.JLabel yyyyyyyyyyyy;
    private javax.swing.JTextField zzzzzzzzzzzzz;
    private javax.swing.JScrollPane zzzzzzzzzzzzzzzzzzz;
    // End of variables declaration//GEN-END:variables
}
